import * as stylex from '@stylexjs/stylex'
import { tokens } from './tokens.stylex'

const reveal = stylex.keyframes({
  from: { opacity: 0, transform: 'translateY(0.6rem)' },
  to: { opacity: 1, transform: 'none' },
})

const mq720 = '@media (max-width: 720px)'
const mq400 = '@media (max-width: 400px)'
const mqReducedMotion = '@media (prefers-reduced-motion: reduce)'

export const sharedStyles = stylex.create({
  container: {
    width: `min(100%, calc(${tokens.maxWidth} + (2 * ${tokens.gutter})))`,
    marginInline: 'auto',
    paddingInline: tokens.gutter,
  },
  btn: {
    display: 'inline-flex',
    minHeight: '44px',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1.5rem',
    paddingBlock: '0.7rem',
    paddingInline: '0.9rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.ruleStrong,
    borderRadius: 0,
    color: tokens.paper,
    backgroundColor: 'transparent',
    fontFamily: tokens.fontMono,
    fontWeight: 600,
    fontSize: tokens.fontControl,
    lineHeight: 1,
    letterSpacing: '0.02em',
    textDecoration: 'none',
    cursor: 'pointer',
    transitionProperty: 'background, border-color, color',
    transitionDuration: '140ms',
    transitionTimingFunction: 'ease',
    ':hover': {
      color: tokens.paper,
      borderColor: tokens.paperMuted,
      backgroundColor: tokens.steel,
    },
    [mq400]: {
      width: '100%',
    },
  },
  btnPrimary: {
    color: tokens.inkDeep,
    borderColor: tokens.signal,
    backgroundColor: tokens.signal,
    ':hover': {
      color: tokens.inkDeep,
      borderColor: tokens.signalHot,
      backgroundColor: tokens.signalHot,
    },
  },
  btnText: {
    paddingInline: '0.15rem',
    borderColor: 'transparent',
    color: tokens.signalHot,
    ':hover': {
      color: tokens.paper,
      borderColor: 'transparent',
      backgroundColor: 'transparent',
    },
  },
  ctaGroup: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: tokens.space3,
    marginTop: tokens.space5,
    [mq400]: {
      alignItems: 'stretch',
      flexDirection: 'column',
    },
  },
  page: {
    paddingBlock: `${tokens.space7} ${tokens.space8}`,
    backgroundColor: tokens.ink,
    overflowX: 'clip',
    [mq720]: {
      paddingBlock: tokens.space7,
    },
  },
  fullBleedHero: {
    position: 'relative',
    display: 'flex',
    minHeight: 'min(42rem, calc(100vh - 4.75rem))',
    width: '100vw',
    marginBlockStart: `calc(${tokens.space7} * -1)`,
    marginBlockEnd: tokens.space7,
    marginInlineStart: 'calc((100% - 100vw) / 2)',
    marginInlineEnd: 0,
    flexDirection: 'column',
    justifyContent: 'center',
    gap: tokens.space4,
    overflow: 'hidden',
    padding: `${tokens.space7} clamp(1.5rem, 5vw, 5rem)`,
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.ruleStrong,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.rule,
  },
  heroBandChild: {
    position: 'relative',
    zIndex: 1,
    width: 'min(100%, 67rem)',
    marginInlineStart: 0,
    marginInlineEnd: 'auto',
  },
  pageKicker: {
    fontFamily: tokens.fontMono,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: tokens.paperSubtle,
    fontSize: tokens.fontLabel,
  },
  notFoundTitle: {
    marginBottom: tokens.space4,
    fontSize: tokens.fontHero,
    fontWeight: 600,
    lineHeight: 1.02,
    letterSpacing: '-0.035em',
  },
  pageIntro: {
    maxWidth: '42rem',
    marginInline: 0,
    color: tokens.paperMuted,
    fontSize: tokens.fontIntro,
    lineHeight: 1.55,
  },
  revealHero: {
    animationName: reveal,
    animationDuration: '500ms',
    animationTimingFunction: 'ease-out',
    animationFillMode: 'both',
    [mqReducedMotion]: {
      animationName: 'none',
    },
  },
  evidenceFrame: {
    margin: 0,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.ruleStrong,
    backgroundColor: tokens.graphite,
  },
  evidenceFrameChrome: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '1rem',
    paddingBlock: '0.65rem',
    paddingInline: '0.85rem',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.rule,
    color: tokens.paperSubtle,
    fontFamily: tokens.fontMono,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    fontSize: tokens.fontMeta,
    [mq400]: {
      alignItems: 'flex-start',
      flexDirection: 'column',
      gap: '0.2rem',
    },
  },
  evidenceFrameImage: {
    width: '100%',
  },
  evidenceFrameFigcaption: {
    display: 'flex',
    gap: '0.75rem',
    paddingBlock: '0.7rem',
    paddingInline: '0.85rem',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.rule,
    color: tokens.paperMuted,
    fontFamily: tokens.fontMono,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    fontSize: tokens.fontMeta,
  },
  evidenceFrameFigcaptionSpan: {
    color: tokens.signal,
  },
})
