import * as stylex from '@stylexjs/stylex'
import { tokens } from './tokens.stylex'

const reveal = stylex.keyframes({
  from: { opacity: 0, transform: 'translateY(0.6rem)' },
  to: { opacity: 1, transform: 'none' },
})

const mq720 = '@media (max-width: 720px)'
const mq400 = '@media (max-width: 400px)'
const mqReducedMotion = '@media (prefers-reduced-motion: reduce)'

export const sharedStyles = stylex.create({
  container: {
    width: `min(100%, calc(${tokens.maxWidth} + (2 * ${tokens.gutter})))`,
    marginInline: 'auto',
    paddingInline: tokens.gutter,
  },
  containerNarrow: {
    width: `min(100%, calc(${tokens.contentWidth} + (2 * ${tokens.gutter})))`,
  },
  indexLabel: {
    fontFamily: tokens.fontMono,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: tokens.paperSubtle,
    fontSize: '0.7rem',
  },
  indexLabelSpan: {
    marginRight: '0.75rem',
    color: tokens.signal,
  },
  sectionHeading: {
    marginBottom: tokens.space6,
    paddingTop: tokens.space3,
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.ruleStrong,
  },
  sectionHeadingSplit: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: tokens.space5,
    [mq720]: {
      gridTemplateColumns: '1fr',
    },
  },
  sectionHeadingNote: {
    maxWidth: '28rem',
    color: tokens.paperSubtle,
    fontFamily: tokens.fontMono,
    fontSize: '0.76rem',
    lineHeight: 1.6,
  },
  btn: {
    display: 'inline-flex',
    minHeight: '44px',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1.5rem',
    paddingBlock: '0.7rem',
    paddingInline: '0.9rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.ruleStrong,
    borderRadius: 0,
    color: tokens.paper,
    backgroundColor: 'transparent',
    fontFamily: tokens.fontMono,
    fontWeight: 600,
    fontSize: '0.78rem',
    lineHeight: 1,
    letterSpacing: '0.02em',
    textDecoration: 'none',
    cursor: 'pointer',
    transitionProperty: 'background, border-color, color',
    transitionDuration: '140ms',
    transitionTimingFunction: 'ease',
    ':hover': {
      color: tokens.paper,
      borderColor: tokens.paperMuted,
      backgroundColor: tokens.steel,
    },
    [mq400]: {
      width: '100%',
    },
  },
  btnPrimary: {
    color: tokens.inkDeep,
    borderColor: tokens.signal,
    backgroundColor: tokens.signal,
    ':hover': {
      color: tokens.inkDeep,
      borderColor: tokens.signalHot,
      backgroundColor: tokens.signalHot,
    },
  },
  btnText: {
    paddingInline: '0.15rem',
    borderColor: 'transparent',
    color: tokens.signalHot,
    ':hover': {
      color: tokens.paper,
      borderColor: 'transparent',
      backgroundColor: 'transparent',
    },
  },
  ctaGroup: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: tokens.space3,
    marginTop: tokens.space5,
    [mq400]: {
      alignItems: 'stretch',
      flexDirection: 'column',
    },
  },
  section: {
    margin: 0,
    paddingBlock: tokens.space7,
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.ruleStrong,
  },
  sectionTitle: {
    maxWidth: '14ch',
    marginBottom: tokens.space4,
  },
  sectionBody: {
    maxWidth: tokens.contentWidth,
    color: tokens.paperMuted,
  },
  sectionBodyParagraph: {
    ':not(:first-child)': {
      marginTop: tokens.space4,
    },
  },
  sectionBodyList: {
    paddingLeft: '1.2rem',
    ':not(:first-child)': {
      marginTop: tokens.space4,
    },
  },
  honestyBlock: {
    maxWidth: '48rem',
    marginTop: tokens.space5,
    padding: tokens.space4,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.ruleStrong,
    borderLeftWidth: '4px',
    borderLeftColor: tokens.signal,
    backgroundColor: tokens.graphite,
    color: tokens.paperMuted,
  },
  honestyBlockLabel: {
    marginBottom: tokens.space2,
    color: tokens.signal,
    fontFamily: tokens.fontMono,
    fontSize: '0.7rem',
    lineHeight: 1,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  page: {
    paddingBlock: `${tokens.space7} ${tokens.space8}`,
    backgroundColor: tokens.ink,
    [mq720]: {
      paddingBlock: tokens.space7,
    },
  },
  pageHeader: {
    display: 'grid',
    gridTemplateColumns: 'minmax(12rem, 0.45fr) minmax(0, 1fr)',
    gap: tokens.space6,
    marginBottom: tokens.space7,
    paddingTop: tokens.space3,
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.ruleStrong,
    [mq720]: {
      gridTemplateColumns: '1fr',
    },
  },
  pageKicker: {
    fontFamily: tokens.fontMono,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: tokens.paperSubtle,
    fontSize: '0.7rem',
  },
  pageIntro: {
    maxWidth: '42rem',
    color: tokens.paperMuted,
    fontSize: 'clamp(1.08rem, 2vw, 1.35rem)',
    lineHeight: 1.55,
  },
  externalNote: {
    marginTop: tokens.space5,
    color: tokens.paperSubtle,
    fontSize: '0.82rem',
  },
  revealHero: {
    animationName: reveal,
    animationDuration: '500ms',
    animationTimingFunction: 'ease-out',
    animationFillMode: 'both',
    [mqReducedMotion]: {
      animationName: 'none',
    },
  },
  statusLine: {
    fontFamily: tokens.fontMono,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: tokens.paperMuted,
    fontSize: '0.68rem',
  },
  statusDot: {
    display: 'inline-block',
    width: '0.55rem',
    height: '0.55rem',
    marginRight: '0.55rem',
    backgroundColor: tokens.signal,
  },
  evidenceFrame: {
    margin: 0,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.ruleStrong,
    backgroundColor: tokens.graphite,
  },
  evidenceFrameChrome: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '1rem',
    paddingBlock: '0.65rem',
    paddingInline: '0.85rem',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.rule,
    color: tokens.paperSubtle,
    fontFamily: tokens.fontMono,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    fontSize: '0.62rem',
    [mq400]: {
      alignItems: 'flex-start',
      flexDirection: 'column',
      gap: '0.2rem',
    },
  },
  evidenceFrameImage: {
    width: '100%',
  },
  evidenceFrameFigcaption: {
    display: 'flex',
    gap: '0.75rem',
    paddingBlock: '0.7rem',
    paddingInline: '0.85rem',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.rule,
    color: tokens.paperMuted,
    fontFamily: tokens.fontMono,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    fontSize: '0.66rem',
  },
  evidenceFrameFigcaptionSpan: {
    color: tokens.signal,
  },
  problemList: {
    display: 'grid',
    gap: 0,
    marginTop: tokens.space5,
    marginBottom: 0,
    marginInline: 0,
    padding: 0,
    listStyle: 'none',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.rule,
  },
  problemListItem: {
    paddingBlock: tokens.space3,
    paddingInlineStart: '2rem',
    paddingInlineEnd: 0,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.rule,
    color: tokens.paperMuted,
    position: 'relative',
    '::before': {
      content: '"—"',
      position: 'absolute',
      left: 0,
      color: tokens.signal,
    },
  },
})
