import * as stylex from '@stylexjs/stylex'

export const tokens = stylex.defineVars({
  ink: 'var(--ink)',
  inkDeep: 'var(--ink-deep)',
  graphite: 'var(--graphite)',
  steel: 'var(--steel)',
  rule: 'var(--rule)',
  inkDeepTranslucent: 'oklch(0.075 0.004 255 / 0.94)',
  fontMeta: '0.65rem',
  fontLabel: '0.7rem',
  fontCaption: '0.72rem',
  fontUi: '0.75rem',
  fontNote: '0.76rem',
  fontControl: '0.78rem',
  fontNav: '0.82rem',
  fontNavSm: '0.69rem',
  fontLead: '0.84rem',
  fontBodySm: '0.88rem',
  fontBodyMd: '0.9rem',
  fontSubhead: '1.05rem',
  fontSubheadLg: '1.12rem',
  fontSection: '1.2rem',
  fontSmall: '0.8rem',
  fontTitleSm: '1.1rem',
  fontDisplayMd: '1.25rem',
  fontBody: '1rem',
  fontEmphasis: '1.35rem',
  fontHero: 'clamp(3rem, 7vw, 6rem)',
  fontIntro: 'clamp(1.1rem, 2vw, 1.35rem)',
  fontSectionTitle: 'clamp(2.5rem, 5vw, 4.6rem)',
  fontQuote: 'clamp(1.35rem, 2.4vw, 2rem)',
  fontBodyLead: 'clamp(1.05rem, 2vw, 1.3rem)',
  ruleStrong: 'var(--rule-strong)',
  paper: 'var(--paper)',
  paperMuted: 'var(--paper-muted)',
  paperSubtle: 'var(--paper-subtle)',
  signal: 'var(--signal)',
  signalHot: 'var(--signal-hot)',
  fontSans: 'var(--font-sans)',
  fontMono: 'var(--font-mono)',
  maxWidth: 'var(--max-width)',
  contentWidth: 'var(--content-width)',
  gutter: 'var(--gutter)',
  space1: 'var(--space-1)',
  space2: 'var(--space-2)',
  space3: 'var(--space-3)',
  space4: 'var(--space-4)',
  space5: 'var(--space-5)',
  space6: 'var(--space-6)',
  space7: 'var(--space-7)',
  space8: 'var(--space-8)',
})
